### ISSUE TITLE
Not able to install on Julia 1.3.1 because of Plots package

### ISSUE THREAD

**Issue by caxelrud** [lucianolorenti/SpectralClustering.jl#6]
I have Plots v 0.29.9
I got this message:

ERROR: Unsatisfiable requirements detected for package Plots [91a5bcdd]:
 Plots [91a5bcdd] log:
 ├─possible versions are: [0.12.1-0.12.4, 0.13.0-0.13.1, 0.14.0-0.14.2, 0.15.0-0.15.1, 0.16.0, 0.17.0-0.17.4, 0.18.0, 0.19.0-0.19.3, 0.20.0-0.20.6, 0.21.0, 0.22.0-0.22.5, 0.23.0-0.23.2, 0.24.0, 0.25.0-0.25.3, 0.26.0-0.26.3, 0.27.0-0.27.1, 0.28.0-0.28.4, 0.29.0-0.29.9, 1.0.0-1.0.5] or uninstalled
 ├─restricted to versions 0.27 by SpectralClustering [a9453432], leaving only versions 0.27.0-0.27.1
 │ └─SpectralClustering [a9453432] log:
 │   ├─possible versions are: 0.1.1 or uninstalled
 │   └─SpectralClustering [a9453432] is fixed to version 0.1.1
 └─restricted to versions 0.29.6 by an explicit requirement — no versions left

**Comment by lucianolorenti** [comment]
Hi! Thank you for the heads up. I pushed a new version relaxing the constraints of the requirements. The tests are passing in julia 1.3 and julia 1.4. I suppose that soon the new version will be merged in the Julia Registry.
