### ISSUE TITLE
incorrect scaling in embedding(cfg::ShiMalikLaplacian, L::NormalizedLaplacian)

### ISSUE THREAD

**Issue by kragol** [lucianolorenti/SpectralClustering.jl#8]
The scaling used in `embedding(cfg::ShiMalikLaplacian, L::NormalizedLaplacian)` at `embedding.jl:317` appears to be incorrect.

According to the Shi and Malik paper (eq (18)), the eigenvectors of the normalized Laplacian should be multiplied by `D^(-1/2)`. In the code, they are multiplied by `D^(1/2)` instead. 

Note that this has no impact unless the normalization option in `ShiMalikLaplacian` is turned off (it defaults to on), so I guess most use cases are not impacted.

**Comment by lucianolorenti** [comment]
Hi! Thank you for the catch. I am going to write a failing test for this problem so merging your PR will fix it.
